### ISSUE TITLE
Error: list

### ISSUE THREAD

**Issue by firmai** [berknology/text-preprocessing#3]
Thanks for the package, its neat to have everything in one place.

I am bumping into the following problem:

This works, but as soon as I add the punctuation and other functions there is a problem

![image](https://user-images.githubusercontent.com/26666267/122239775-20d47c00-ceb9-11eb-9ac1-f4491262054c.png)

![image](https://user-images.githubusercontent.com/26666267/122239841-3053c500-ceb9-11eb-86e8-89d003720a5a.png)

**Comment by berknology** [comment]
Hi @firmai, thanks for reporting the issue. It is caused by the input and output type requirements of the different preprocess functions which are run in a sequential manner.
The output of the [lemmatize_word ](https://github.com/berknology/text-preprocessing/blob/master/text_preprocessing/text_preprocessing.py#L266) function is **list of str**, while the input of the [remove_punctuation ](https://github.com/berknology/text-preprocessing/blob/master/text_preprocessing/text_preprocessing.py#L103) function is a **str**.

Maybe you can `remove_punctuation` function in front of `remove_stopword`?
